name: Flask App CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build Docker image
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-app .

  # Job to run tests
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the build job
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Run the tests (you can replace this with more complex tests)
      - name: Run unit tests
        run: |
          docker run flask-app python -m unittest discover

  # Job to deploy the app (You can customize this for cloud deployment)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures this job runs after the test job
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application (this is just a placeholder)
      - name: Deploy Flask app
        run: |
          echo "Deploying Flask app..."
          # Add deployment steps here (e.g., deploy to Heroku, AWS, etc.)
