name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login localhost:443 -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t localhost:443/my-flask-app:latest ./app

    - name: Push Docker image to local registry
      run: |
        docker push localhost:443/my-flask-app:latest
